baseURL = "https://kentbryan404.github.io/"
languageCode = "zh-cn"
title = "Zane BlackWood Digital Garden"
theme = "digitalgarden"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "My Digital Garden"
  images = ['/digital-garden-logo.png']
  enableSearch = true

[Params.newsletter]
  title = ""
  description = "A curated weekly digest once a week to your mailbox"

  # Supports buttondown, substack and revue
  provider = "buttondown"

  # Buttondown - URL from share page; Refer: https://blog.buttondown.email/2019/10/11/adding-a-buttondown-subscription-form-to-webflow#getting-your-subscription-url
  # Substack - URL of the newsletter homepage; Example: https://on.substack.com/
  # Revue - Username
  path = "https://buttondown.email/api/emails/embed-subscribe/"

[menu]
[[menu.main]]
  name = '首页'
  url = '/'
  weight = 1






[[menu.main]]
  name = '服务器'
  params.header = true
  weight = 1000

[[menu.main]]
  name = 'Nas相关'
  url = '/1100'
  weight = 1100

[[menu.main]]
  name = '视听影音'
  url = '/1200'
  weight = 1200


[[menu.main]]
  name = '私有云存储'
  url = '/1300'
  weight = 1300



[[menu.main]]
  name = '博客分享'
  url = '/1400'
  weight = 1400


[[menu.main]]
  name = '笔记软件'
  url = '/1500'
  weight = 1500


[[menu.main]]
  name = '图书馆'
  url = '/1600'
  weight = 1600




[[menu.main]]
name = '技术文档'
params.header = true
weight = 5000




#[[menu.main]]
#  name = 'Content'
#  params.header = true
#  weight = 2
#[[menu.main]]
#  name = 'Articles'
#  url = '/articles'
#  weight = 3
#[[menu.main]]
#  name = '运维'
#  weight = 4
#  params.header = true
#[[menu.main]]
#  name = 'op'
#  url = '/op'
#  weight = 4
#[[menu.main]]
#  name = 'Portfolio'
#  url = '/portfolio'
#  weight = 5
#[[menu.main]]
#  name = 'Stack'
#  url = '/stack'
#  weight = 6















[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 99999
[[menu.main]]
  name = 'Polywork'
  url = 'https://polywork.com'
  weight = 100000












[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com'
  weight = 1
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com'
  weight = 2
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://linkedin.com'
  weight = 3
[[menu.social]]
  name = 'Instagram'
  url = 'https://instagram.com'
  weight = 4
[[menu.social]]
  name = 'Dribbble'
  url = 'https://dribbble.com'
  weight = 5
[[menu.social]]
  name = 'Codepen'
  url = 'https://codepen.io'
  weight = 6
[[menu.social]]
  name = 'Twitch'
  url = 'https://twitch.com'
  weight = 7
[[menu.social]]
  name = 'Email'
  url = 'mailto:user@example.org'
  weight = 8
[[menu.social]]
  name = 'RSS'
  url = '/articles/index.xml'
  weight = 9


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
